# Tomcat
server:
  port: 8080

spring:
  # 环境 dev|test|pro
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      maxFileSize: 20971520 #20MB
      maxRequestSize: 104857600 #100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #解决swaggerUI不匹配接口

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      # 默认数据库表下划线命名
      table-underline: true

# 签名
api.signature: '{"417c4f3f30d34043": "5d940d7bb69d428eaf813a243591aba3"}'
